name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what happened, and what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: How to reproduce?
      value: |
        1. 
        2. 
        3. 
        ...
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: What device are you using?
      description: Tell us which type of device, operating system, and OS version you are running.
      placeholder: "iOS 15.2"
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Which browsers are affected by this problem?
      description: Tell us which browsers you were using, or if this is a server-side problem.
      placeholder: "Safari 22 or NodeJS"
    validations:
      required: true
  - type: textarea
    id: extras
    attributes:
      label: Additional context
      description: Anything else you want to tell us? You can also attach screenshots and logs to help us if available.
