name: Feature Request
description: Suggest a feature for this project.
title: "[Feature Request]: "
labels: [feature]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is this request related to a problem?
      description: Give a clear and concise explanation of what the problem is.
  - type: textarea
    id: solution
    attributes:
      label: What is your proposed solution to this problem?
      description: Give a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe any alternatives you've considered.
      description: Give a clear and concise description of any alternatives you've considered.
  - type: textarea
    id: extras
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request.
    